//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isport_payment
{

    /// <summary>
    /// pay_dtac_cancel class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class pay_dtac_cancel
    {
        protected global::System.Web.UI.MobileControls.Form Form1;
    }
}
