//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isport_foxhun
{
    using System;
    using System.Collections.Generic;
    
    public partial class foxhun_player_history
    {
        public string id { get; set; }
        public string player_id { get; set; }
        public string region { get; set; }
        public string team { get; set; }
        public System.DateTime datetime { get; set; }
        public int index { get; set; }
        public Nullable<int> seq { get; set; }
        public string position { get; set; }
        public string name { get; set; }
        public string control { get; set; }
        public string attack { get; set; }
        public string defense { get; set; }
        public string physical { get; set; }
        public string mental { get; set; }
        public string adversary { get; set; }
        public string contact { get; set; }
        public string HT { get; set; }
        public string FT { get; set; }
        public Nullable<int> competition { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> see { get; set; }
        public string detail { get; set; }
        public Nullable<int> wight { get; set; }
        public Nullable<int> hight { get; set; }
        public Nullable<int> age { get; set; }
        public string country { get; set; }
        public string image { get; set; }
        public Nullable<int> sum { get; set; }
        public string tacktick { get; set; }
    }
}
