//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class foxhun_match
{
    public string id { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
    public Nullable<System.DateTime> updatedate { get; set; }
    public string matchdate { get; set; }
    public string team1 { get; set; }
    public string team2 { get; set; }
    public string ht { get; set; }
    public string ft { get; set; }
}

public partial class foxhun_player
{
    public string id { get; set; }
    public string region { get; set; }
    public string team { get; set; }
    public System.DateTime datetime { get; set; }
    public int index { get; set; }
    public Nullable<int> seq { get; set; }
    public string position { get; set; }
    public string name { get; set; }
    public string control { get; set; }
    public string attack { get; set; }
    public string tacktick { get; set; }
    public string defense { get; set; }
    public string physical { get; set; }
    public string mental { get; set; }
    public string adversary { get; set; }
    public string contact { get; set; }
    public string HT { get; set; }
    public string FT { get; set; }
    public Nullable<int> competition { get; set; }
    public Nullable<int> score { get; set; }
    public Nullable<int> see { get; set; }
    public string detail { get; set; }
    public Nullable<int> wight { get; set; }
    public Nullable<int> hight { get; set; }
    public Nullable<int> age { get; set; }
    public string country { get; set; }
    public string image { get; set; }
    public Nullable<int> sum { get; set; }
    public string team_id { get; set; }
    public Nullable<int> number { get; set; }
    public string birthday { get; set; }
}

public partial class foxhun_player_history
{
    public string id { get; set; }
    public string player_id { get; set; }
    public string region { get; set; }
    public string team { get; set; }
    public System.DateTime datetime { get; set; }
    public int index { get; set; }
    public Nullable<int> seq { get; set; }
    public string position { get; set; }
    public string name { get; set; }
    public string control { get; set; }
    public string attack { get; set; }
    public string defense { get; set; }
    public string tacktick { get; set; }
    public string physical { get; set; }
    public string mental { get; set; }
    public string adversary { get; set; }
    public string contact { get; set; }
    public string HT { get; set; }
    public string FT { get; set; }
    public Nullable<int> competition { get; set; }
    public Nullable<int> score { get; set; }
    public Nullable<int> see { get; set; }
    public string detail { get; set; }
    public Nullable<int> wight { get; set; }
    public Nullable<int> hight { get; set; }
    public Nullable<int> age { get; set; }
    public string country { get; set; }
    public string image { get; set; }
    public Nullable<int> sum { get; set; }
}

public partial class foxhun_province
{
    public int pvnID { get; set; }
    public string lclID { get; set; }
    public Nullable<int> zneID { get; set; }
    public string pvnName { get; set; }
    public System.DateTime pvnModifiedOn { get; set; }
    public int pvnModifiedBy { get; set; }
}

public partial class foxhun_region
{
    public string id { get; set; }
    public int index { get; set; }
    public Nullable<int> seq { get; set; }
    public Nullable<System.DateTime> datetime { get; set; }
    public string name { get; set; }
    public string detail { get; set; }
}

public partial class foxhun_scout
{
    public string id { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
    public string match_id { get; set; }
    public string user_id { get; set; }
    public string player { get; set; }
}

public partial class foxhun_team
{
    public string id { get; set; }
    public string region { get; set; }
    public int index { get; set; }
    public Nullable<int> seq { get; set; }
    public Nullable<System.DateTime> create_datetime { get; set; }
    public Nullable<System.DateTime> update_date { get; set; }
    public string name { get; set; }
    public string detail { get; set; }
    public string email { get; set; }
    public string image { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string contact { get; set; }
    public string contact1 { get; set; }
    public string contact2 { get; set; }
    public string phone { get; set; }
    public string phone1 { get; set; }
    public string contact3 { get; set; }
    public string file1 { get; set; }
    public string file2 { get; set; }
    public string file3 { get; set; }
    public string file4 { get; set; }
    public string file5 { get; set; }
    public string file6 { get; set; }
    public string file7 { get; set; }
    public string file8 { get; set; }
    public string file9 { get; set; }
    public string file10 { get; set; }
    public string contact4 { get; set; }
    public string contact5 { get; set; }
    public string contact6 { get; set; }
    public string phone2 { get; set; }
    public string phone3 { get; set; }
    public string phone4 { get; set; }
    public string phone5 { get; set; }
    public string phone6 { get; set; }
}

public partial class foxhun_users
{
    public string id { get; set; }
    public Nullable<System.DateTime> createdate { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string role { get; set; }
    public string team_id { get; set; }
}

public partial class usp_foxhun_regionselectall_Result
{
    public string id { get; set; }
    public int index { get; set; }
    public Nullable<int> seq { get; set; }
    public Nullable<System.DateTime> datetime { get; set; }
    public string name { get; set; }
    public string detail { get; set; }
}

public partial class usp_foxhun_regionselectbyid_Result
{
    public string id { get; set; }
    public int index { get; set; }
    public Nullable<int> seq { get; set; }
    public Nullable<System.DateTime> datetime { get; set; }
    public string name { get; set; }
    public string detail { get; set; }
}
