//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isport_foxhun
{
    using System;
    using System.Collections.Generic;
    
    public partial class foxhun_scout
    {
        public string id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string match_id { get; set; }
        public string user_id { get; set; }
        public string player_id { get; set; }
        public string team_id { get; set; }
    }
}
