//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isport_foxhun
{
    using System;
    using System.Collections.Generic;
    
    public partial class foxhun_team
    {
        public string id { get; set; }
        public string region { get; set; }
        public int index { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string contact { get; set; }
        public string contact1 { get; set; }
        public string contact2 { get; set; }
        public string phone { get; set; }
        public string phone1 { get; set; }
        public string contact3 { get; set; }
        public string file1 { get; set; }
        public string file2 { get; set; }
        public string file3 { get; set; }
        public string file4 { get; set; }
        public string file5 { get; set; }
        public string file6 { get; set; }
        public string file7 { get; set; }
        public string file8 { get; set; }
        public string file9 { get; set; }
        public string file10 { get; set; }
        public string contact4 { get; set; }
        public string contact5 { get; set; }
        public string contact6 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string phone4 { get; set; }
        public string phone5 { get; set; }
        public string phone6 { get; set; }
    }
}
