//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isport_foxhun
{
    using System;
    using System.Collections.Generic;
    
    public partial class foxhun_match
    {
        public string id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string matchdate { get; set; }
        public string team1 { get; set; }
        public string team2 { get; set; }
        public string ht { get; set; }
        public string ft { get; set; }
        public string field { get; set; }
    }
}
